[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
contest_platform = "CqJqQSsEv35yyHbA1Q4VXjyLRzLXoZkcaxWPsnzR6TCq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
