pub const GLOBAL_STATE_SEED: &[u8] = b"GLOBAL-STATE-SEED";
pub const CONTEST_CREATE_SEED: &[u8] = b"CONTEST-CREATE-SEED";
pub const TOKEN_VAULT_SEED: &[u8] = b"TOKEN-VAULT-SEED";
pub const CONTEST_INFO_SEED: &[u8] = b"CONTEST-INFO-SEED";